Add report generation for JUNIT tests
Signed-off-by: Travis F. Collins <travis.collins@analog.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,6 +50,11 @@ jobs:
       - name: Test
         run: |
                 pytest -vs --cov=adi --scan-verbose --emu --junitxml="results.xml" -k 'not prod'
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'results.xml'
 
       - name: Report coverage
         if: (github.event_name != 'pull_request') && (matrix.python-version == 3.6)
@@ -67,6 +72,11 @@ jobs:
         run: |
                 pip uninstall -y paramiko
                 pytest -vs --scan-verbose --emu --junitxml="results.xml" -k 'not prod'
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'results.xml'
 
 
   Lint:
